version: "3.4"

services:

  db:
    image: mysql-data:one
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql

  earness:
    image: earness:one
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

      


